In [2]:
#@title TASK 1
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

train = pd.read_csv("occupancy_train.txt")
test = pd.read_csv("occupancy_test.txt")

X_train = train[["Humidity", "Light", "HumidityRatio"]]
y_train = train["Occupancy"]

X_test = test[["Humidity", "Light", "HumidityRatio"]]
y_test = test["Occupancy"]

accuracies = []

for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append((k, acc))
    print(f"K={k}, Accuracy={acc:.4f}")

best_k, best_acc = max(accuracies, key=lambda x: x[1])
print(f"\nBest Accuracy: {best_acc:.4f} at K={best_k}")

K=1, Accuracy=0.9403
K=2, Accuracy=0.9253
K=3, Accuracy=0.9572
K=4, Accuracy=0.9448
K=5, Accuracy=0.9553
K=6, Accuracy=0.9527
K=7, Accuracy=0.9632
K=8, Accuracy=0.9614
K=9, Accuracy=0.9647
K=10, Accuracy=0.9647

Best Accuracy: 0.9647 at K=9


In [3]:
#@title TASK 2

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

# Chi-squared distance
def chi_squared_distance(x, y):
    return np.sum((x - y) ** 2 / (x + y + 1e-10))

# Custom KNN
class CustomKNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        predictions = []
        for test_point in X_test:
            distances = [chi_squared_distance(test_point, x) for x in self.X_train]

            k_indices = np.argsort(distances)[:self.k]
            k_labels = [self.y_train[i] for i in k_indices]

            predictions.append(max(set(k_labels), key=k_labels.count))
        return np.array(predictions)

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #split 80/20

knn = CustomKNN(k=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Custom KNN Accuracy:", acc)
print("Confusion Matrix:\n", cm)


Custom KNN Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
